/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* always defined to indicate that i18n is enabled */
#define ENABLE_NLS 1

/* Define to the gettext package of the program */
#define GETTEXT_PACKAGE "openanno"

/* Define to 1 if you have the `bind_textdomain_codeset' function. */
#define HAVE_BIND_TEXTDOMAIN_CODESET 1

/* Define to 1 if you have the `dcgettext' function. */
#define HAVE_DCGETTEXT 1

/* Define if the GNU gettext() function is already present or preinstalled. */
#define HAVE_GETTEXT 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if your <locale.h> file defines LC_MESSAGES. */
#define HAVE_LC_MESSAGES 1

/* Define to 1 if you have the `physfs' library (-lphysfs). */
#define HAVE_LIBPHYSFS 1

/* Define to 1 if you have the `SDL_gfx' library (-lSDL_gfx). */
#define HAVE_LIBSDL_GFX 1

/* Define to 1 if you have the `SDL_image' library (-lSDL_image). */
#define HAVE_LIBSDL_IMAGE 1

/* Define to 1 if you have the `SDL_mixer' library (-lSDL_mixer). */
#define HAVE_LIBSDL_MIXER 1

/* Define to 1 if you have the `SDL_ttf' library (-lSDL_ttf). */
#define HAVE_LIBSDL_TTF 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "openanno"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the programs data directory */
#define PACKAGE_DATA_DIR 

/* Define to the programs documentation directory */
#define PACKAGE_DOC_DIR 

/* Define to the programs help directory */
#define PACKAGE_HELP_DIR 

/* Package local directory */
#define PACKAGE_LOCALE_DIR "/usr/local/share/locale"

/* Define to the programs menu links directory */
#define PACKAGE_MENU_DIR 

/* Define to the full name of this package. */
#define PACKAGE_NAME "openanno"

/* Define to the programs source directory */
#define PACKAGE_SOURCE_DIR 

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "openanno 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "openanno"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.1"
